### PR TITLE
Add func to get available resources on ocp cluster

### PR DESCRIPTION
**Pull request by kasturinarra**
Add func to get available cpu & mem resources from schedulable nodes in ocp cluster

### CODE REVIEW

**Comment by kasturinarra** [comment]
@jbpratt @adtandale @btjd could you please help review ? Thanks !!

**Comment by adtandale** [comment]
Can you please fix lint errors?

**Comment by kasturinarra** [comment]
> Can you please fix lint errors?

yes, had some questions and got them resolved from badre, will work on those, thanks !!

**Comment by kasturinarra** [comment]
> > Can you please fix lint errors?
> 
> yes, had some questions and got them resolved from badre, will work on those, thanks !!

Done, fixed !!

**Comment by btjd** [comment]
retest

**Comment by btjd** [comment]
retest

**Review by btjd — APPROVED** [review]
LGTM

**Review by adtandale — APPROVED** [review]
LGTM

**Pull request merged**
