### PR TITLE
CSSWA-544 Only run resources tests for pre check-in

### PR DESCRIPTION
**Pull request by btjd**
Only run resources test for pre check-in

### CODE REVIEW

**Review by Dannyb48 — APPROVED** [review]
LGTM

**Comment by Dannyb48** [comment]
retest

**Review by Simranpal — APPROVED** [review]
Thanks, looks good!

**Comment by btjd** [comment]
retest

**Comment by btjd** [comment]
retest

**Comment by btjd** [comment]
retest

**Comment by btjd** [comment]
I ran all the tests under resources on the same cluster directly with pytest, module by module and they eventually all passed. Most failures were observed on ocp_projects.py where a lot of project delete operations would stagnate in "Terminating" and cause timeouts. The only other intermittent failure I saw was in ocp_configs for the update method, but it passed on the second run. The issue I ran into is cited below, but it didn't persist.
https://access.redhat.com/solutions/5114881

**Comment by btjd** [comment]
retest

**Comment by btjd** [comment]
retest

**Comment by Simranpal** [comment]
retest

**Review by adtandale — APPROVED** [review]
The PR has been executed on a different platform and found working.

**Pull request merged**
