### PR TITLE
MPS-45 Get Node status

### PR DESCRIPTION
**Pull request by vikasmulaje**
Add libraries to get all/master/worker nodes status

### CODE REVIEW

**Comment by vikasmulaje** [comment]
@btjd @Dannyb48 @adtandale @jbpratt could you please help review ? Thanks !!
Local logs: http://pastebin.test.redhat.com/990838

**Review by jbpratt — APPROVED** [review]
LGTM!

**Comment by adtandale** [comment]
For legacy and consistency, I do agree with @Dannyb48 .

**Review by adtandale — COMMENTED** [review]
Please change the name of the functions.

**Comment by vikasmulaje** [comment]
Updated the function names

**Review by Dannyb48 — APPROVED** [review]
LGTM

**Review by adtandale — APPROVED** [review]
LGTM

**Pull request merged**
