### PR TITLE
upgrade of check operator installed

### PR DESCRIPTION
**Pull request by adtandale**

### CODE REVIEW

**Comment by adtandale** [comment]
retest

**Comment by adtandale** [comment]
retest

**Comment by adtandale** [comment]
retest

**Comment by adtandale** [comment]
retest

**Comment by adtandale** [comment]
retest

**Comment by btjd** [comment]
retest

**Comment by adtandale** [comment]
retest

**Comment by adtandale** [comment]
retest

**Comment by btjd** [comment]
retest

**Comment by btjd** [comment]
retest

**Comment by btjd** [comment]
retest

**Comment by btjd** [comment]
retest

**Comment by btjd** [comment]
retest

**Comment by btjd** [comment]
retest

**Review by btjd — APPROVED** [review]
LGTM. The CI failures are environmental and a successful run was achieved on a different cluster.

**Comment by adtandale** [comment]
> LGTM. The CI failures are environmental and a successful run was achieved on a different cluster.

Thanks!

**Review by Dannyb48 — APPROVED** [review]
LGTM

**Pull request merged**
