### PR TITLE
[CSSWA-475] VirtualMachine resources/abstractions

### PR DESCRIPTION
**Pull request by gmcrocetti**
Add support for VirtualMachine resource
- Add VM's subresources client
- VM client
- VM abstraction

### CODE REVIEW

**Review by amacmurr — COMMENTED** [review]
Looks good to me!

**Comment by btjd** [comment]
Overall it looks good. The only comment I have is that using this resource requires the CNV to beinstalled correct? In other words, I assume that the target namsepace should have some CRDs present. I think it's worth considering making that check early on. Now I can see the argument being made on whether that check should be implemented at the test level, but it's also worth considering whether it's worth making that check at the resource API level

**Comment by gmcrocetti** [comment]
> Overall it looks good. The only comment I have is that using this resource requires the CNV to beinstalled correct? In other words, I assume that the target namsepace should have some CRDs present. I think it's worth considering making that check early on. Now I can see the argument being made on whether that check should be implemented at the test level, but it's also worth considering whether it's worth making that check at the resource API level

Yeap, CNV is required. I got your point but they're all unit tests, calls to openshift's are all mocked (or the methods calling them). Do you want me to leave something "cooked" for the moment we start making integration tests ?

**Comment by btjd** [comment]
Ship it!

**Pull request merged**
