### PR TITLE
CSSWA-291: drop python2 support

### PR DESCRIPTION
**Pull request by jbpratt**
- CSSWA-291: run pyupgrade --py36-plus
```
    drop old python2 code after confirming that only >=py36 is supported

    - https://github.com/asottile/pyupgrade#redundant-open-modes
    - https://github.com/asottile/pyupgrade#-coding--comment
    - https://github.com/asottile/pyupgrade#super-calls
    - https://github.com/asottile/pyupgrade#rewrites-class-declaration
    - https://github.com/asottile/pyupgrade#forced-strnative-literals
    - https://github.com/asottile/pyupgrade#unpacking-argument-list-comprehensions
    - https://github.com/asottile/pyupgrade#f-strings
    - https://github.com/asottile/pyupgrade#printf-style-string-formatting

    to reproduce these changes run `pyupgrade --py36-plus` on all files
```

- run `make format`

I have intentionally left these as two separate commits, please do not squash them.

### CODE REVIEW

**Comment by jbpratt** [comment]
marking this as draft, this needs rebasing.

**Comment by jbpratt** [comment]
these changes can be reproduced change for change by running `find piqe_ocp_lib/ -type f -name '*.py'  | xargs pyupgrade --py36-plus` then `make format`

**Review by adtandale — COMMENTED** [review]
18 tests failed.

**Review by btjd — APPROVED** [review]
LGTM. Regarding the failing tests though, are you running these against a connected cluster? I am surprised to see that some of the apps and template tests are failing. We should just do our due diligence to make sure nothing is broken.

**Review by adtandale — COMMENTED** [review]
Requesting @Dannyb48 to check test runs from CI

**Comment by btjd** [comment]
I took a brief look at the some of the failures and based on previous experience i think it's due so slow api responses or even the server being unresponsive at times. One notable failure is in the delete_template_based_app where the test is unable to delete the project created by the test. The other failures are around creating and getting an operator group, the tests failed because 'og-project' already exists. I logged into the cluster and manually cleaned all test artifacts. Can we please kick off another run to see how it fairs?

**Comment by Dannyb48** [comment]
To rerun the downstream CI simply add a comment with the phrase `retest`

**Comment by btjd** [comment]
@Dannyb48 Sweet! that's a useful thing to know.

**Review by adtandale — APPROVED** [review]
LGTM

**Pull request merged**
